### ISSUE TITLE
Master Failed to start Network Time Sync

### ISSUE THREAD

**Issue by brockfansler** [JuliusCode/MP4MUSEUM#11]
Related to my issue with needing the root password.

The master repeatedly "Failed to start Network Time Synchronization" and spits out 'systemctl status systemd-timesyncd.service' for details.

**Comment by JuliusCode** [comment]
Hi there,
have you tried the sudo command? afaik this is the official way on raspbian, password is the user password, default „mp4museum“.

the system will encounter errors a lot since it is read only filesystem, but not every service works with that. i tend to ignore it as long as playback works. my knowledge of linux is to limited to fix those things. 

best, Julius.
