### ISSUE TITLE
sync - loop partition not recognized in windows

### ISSUE THREAD

**Issue by Transmodulator** [JuliusCode/MP4MUSEUM#12]
Very frequently, the partition for storing the media doesn't show up in file explorer. Usually is solved by taking the card out and putting it back in. But I have two cardsthat I just can not get the correct partition to appear. The other two partitions always appear. I just wrote the master image to both of them with Raspi imager. Will write again and see if it changes, but haven't had this issue to this extent with the others. Only change is for these I extracted the .img and wrote that instead of writing the .zip

**Comment by Transmodulator** [comment]
Rewrote a card with the .zip with no change. Restarted computer, put in a different card that didn't give me trouble before and still no loop partition. Can't write anything to cards as it stands.

**Comment by JuliusCode** [comment]
Hi,
not sure what setup you have, but i would try to format the card with your operating system first, then use the official raspberry pi imager to write the zip to the card. 
on linux and mac there is a direct link to the card so you can write to it independent of its current contents. not sure how windows does it …

best, Julius.

**Comment by Transmodulator** [comment]
Formatted the card as FAT32 with windows, then wrote normal (not sync) mp4museum v5 to it with official raspberry pi imager. Still only able to access the boot partition. This is only on windows. As you said, works fine with mac.

**Comment by JuliusCode** [comment]
gave it a try on windows today and encountered the same problem you have. 

i am not a big windows guy, but i found my way into diskpart. 
while it correctly lists the partition with „no errors“, for some reason it does not show up with a drive letter.

to create and modify the partitions on the image i have been using Gparted on Raspbian. It seems to work fine with mac and linux, so why bother? just kidding, but i have no clue how to fix this on windows.

if anyone can help, it would be greatly appreciated!

**Comment by JuliusCode** [comment]
so i realised that
- you plug it in, boot shows up
- windows asks if it should format the drive, where you say no
- it will stop trying to mount the card further

this is with boot partition first, then linux, then media.
i tried moving partitions so that there is boot, then media, then linux.
now windows will mount boot and media, then ask to format the linux.

the only way to find and mount the media partition manually is to go through DISKPART on the command line.
so if you urgently need to mount the media partition, you need to find a tutorial online to use DISKPART

![IMG_2921](https://user-images.githubusercontent.com/58294183/203014814-e777e18a-6b86-45cf-8989-90fc6d97d2a8.jpg)
