### ISSUE TITLE
Cannot add subtitles in MP4Museum-Sync / no video on bootup with srt file

### ISSUE THREAD

**Issue by PimTournaye** [JuliusCode/MP4MUSEUM#16]
Adding a loop.srt file in the media partition prevents the playing of the .mp4 file. When removing the .srt file, everything boots just fine.

**Comment by JuliusCode** [comment]
hi,
i could not find any indication that omxplayer-sync supports subtitles.
since it is a hacked version (not by me) of omxplayer, i could imagine that there is code within that would open the subtitle file but then makes playback fail completely. then you‘re just stuck with a black screen, unfortunately.
best, J.
