### ISSUE TITLE
Use both of HDMI 

### ISSUE THREAD

**Issue by metingul** [JuliusCode/MP4MUSEUM#34]
Hello,
I used kodi , libreelec and osmc, your project is really perfect for me, it just takes about in minutes what I want.

I want to ask about Rpi4 hdmi outputs, can I use both of them as video output. (cloning screen)
thank you.

**Comment by ZiggyLever** [comment]
Hi, I also have this issue – is it possible to mirror the HDMI 0 and HDMI 1 outputs on RPI4, so that whichever port will display the video? I'm putting together a number of MP4 Museum PIs for art students to use as a media player that just works – It's been great so far! The reason to mirror the ports is to reduce friction for students.
Thank you

**Comment by JuliusCode** [comment]
hi, 
it seems there has been a problem with my previous answer i had made via email:
as far as i know this is not supported by the player engine (vlc player). all i could find in terms of using mirroring on the outputs is related to running a full desktop.
best, Julius.
