### ISSUE TITLE
VLC does not accept normal keystrokes?

### ISSUE THREAD

**Issue by fridde** [JuliusCode/MP4MUSEUM#6]
This is probably obvious to someone who has more experience with the python bindings, but I was confused by the VLC player in version 5 not accepting any keystrokes from my keyboard.

Is that expected? I tried inserting a --global-key-next=Up into the Instance arguments, but no change. Also: my --repeat argument is ignored, too.

Any ideas? Am I approaching the problem from the wrong side?

**Comment by JuliusCode** [comment]
Hi fridde

the code is not running the vlc binary anymore, but using python-vlc, a module to include the player into the engine that runs the python code.

for your application, that means you would have to change the code (or copy that part) where gpio triggers are handled, at "add event listener". instead of gpio, your script would react to the keystrokes. 

i am not sure if the repeat argument can be applied. to activate loop mode, see here: https://www.olivieraubert.net/vlc/python-ctypes/doc/vlc.Instance-class.html#vlm_set_loop

best, Julius.
